#!/usr/bin/env bash
# Displays DNS A record information for subdomains of a given domain
# shellcheck disable=SC2086

audit_subdomain() {
    local domain=$1
    local subdomain=$2
    local info
    info=$(dig "$subdomain.$domain" +noall +answer | head -1 | awk '{print $4, $5}')
    local record_type
    local destination
    record_type=$(echo $info | awk '{print $1}')
    destination=$(echo $info | awk '{print $2}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -n "$subdomain" ]; then
    audit_subdomain "$domain" "$subdomain"
else
    for sub in www lb-01 web-01 web-02; do
        audit_subdomain "$domain" "$sub"
    done
fi
